name: backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/**"
  # schedule:
  #   # UTCで毎朝7時に実行 (日本時間で16時)
  #   - cron: "0 7 * * *"

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run test -- --coverage
      - run: npm run build

      - run: node dist/index.js & # &はバックグラウンドで起動しておくということ
      - run: npx wait-on -t 10000 http://localhost:8080/api/health # 起動確認のパスにアクセス
      - run: npm run test:api

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage
          path: backend/coverage/**
          retention-days: 5
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: backend/dist/index.js
          retention-days: 5
  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: backend/dist
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.BACKEND_SERVER_SSH_KEY }}
          known_hosts: ${{ secrets.BACKEND_SERVER_KNOWN_HOSTS }}
      - run: rsync -v dist/index.js ${{ secrets.BACKEND_SERVER_USER }}@${{ secrets.BACKEND_SERVER_IP }}:~/index.js
      - run: ssh ${{ secrets.BACKEND_SERVER_USER }}@${{ secrets.BACKEND_SERVER_IP }} sudo systemctl restart backend
      - run: ssh ${{ secrets.BACKEND_SERVER_USER }}@${{ secrets.BACKEND_SERVER_IP }} systemctl status backend
